<?php

/**
 * Implementation of hook_node_info
 *
 * @return unknown
 */
function ebook_node_info() {
	$info = array();
	$info['ebook'] = array(
		'name' => t('EBook'),
		'base' => 'node_content',
		'description' => t('Use for ebook. Every user can upload and view a book.'),
	);
	return $info;
}

/**
 * Implementation of hook_menu()
 */
function ebook_menu() {
  $items['mylibrary'] = array(
    'title' => t('My Library'),
    'page callback' => 'mylibrary_page_callback',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'user-menu',
    'weight' => -5,
  );

  return $items;
}

function mylibrary_page_callback(){
  global $user;
  $build = array();

  $query = db_select('node', 'n')->extend('PagerDefault');
  $nids = $query
    ->fields('n', array('nid', 'created'))
    ->condition('type', 'ebook')
    ->condition('uid', $user->uid)  //books uploaded by the current user
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->limit(variable_get('default_nodes_main', 10))
    ->addTag('node_access')
    ->execute()
    ->fetchCol();

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build += node_view_multiple($nodes);
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
  }
  else {
    drupal_set_message(t('No book entries have been created.'));
  }

  return $build;
}
